# Generated by Django 4.2.6 on 2024-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0003_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
